In [45]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [46]:
corpus=[
    'He likes pizza',
    'She like cold drinks',
    'He loves burgers',
    'They love pasta'
]

In [47]:
vectorizer=CountVectorizer()
X=vectorizer.fit_transform(corpus)
print('Vocabulary',vectorizer.get_feature_names_out())
print('\nBoW Matrix\n',X.toarray())

Vocabulary ['burgers' 'cold' 'drinks' 'he' 'like' 'likes' 'love' 'loves' 'pasta'
 'pizza' 'she' 'they']

BoW Matrix
 [[0 0 0 1 0 1 0 0 0 1 0 0]
 [0 1 1 0 1 0 0 0 0 0 1 0]
 [1 0 0 1 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 1]]
